name: Kontrolná kompilácia DNS klienta

on:
  push:
    branches-ignore:
      - main
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: maven
        architecture: x64
    - name: Build with Maven
      run: mvn -B package
